# Generated by Django 4.1.4 on 2022-12-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platfom', models.CharField(max_length=50)),
                ('pesan', models.CharField(max_length=50)),
            ],
        ),
    ]
